CREATE TABLE pessoa (
    id UUID PRIMARY KEY NOT NULL,
    nome CHARACTER VARYING(255) NOT NULL,
    cpf CHARACTER VARYING(14) NOT NULL UNIQUE,
    telefone CHARACTER VARYING(20) NOT NULL,
    numero CHARACTER VARYING(10) NOT NULL,
    complemento CHARACTER VARYING(255),
    cep CHARACTER VARYING(10) NOT NULL,
    bairro CHARACTER VARYING(255) NOT NULL,
    municipio CHARACTER VARYING(255) NOT NULL,
    estado CHARACTER VARYING(2) NOT NULL,
    created_by CHARACTER VARYING(255) NOT NULL,
    last_modification_by CHARACTER VARYING(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_modification_at TIMESTAMP NOT NULL
);